Nest_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path("iViR0s08y6h{Q6[!Sxnw@(/", admin.site.urls),
    path("", include('core.urls')),
    path("", include('userauths.urls')),
    path("api/", include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import *
from rest_framework import routers

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'categories', CategoryViewSet, basename='categories')

# urlpatterns = router.urls
urlpatterns = [
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('test/', test_end_point, name='test'),
    path('', get_routes),
]

core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'home'
urlpatterns = [
    # Home page
    path("", home_view, name='home'),

    # Products
    path("products", product_list_view, name='product-list'),
    path("product/<pid>", product_detail_view, name="product-detail"),
    path("compare", compare_products_view, name="compare"),
    path("add-to-compare", add_to_compare, name="add-to-compare"),
    path("delete-from-compare", delete_product_from_compare, name="delete-from-compare"),

    # Categories
    path("categories", category_list_view, name='category-list'),
    path("<cid>/products", category_product_list_view, name='category_product_list'),

    # Vendors
    path("vendors", vendor_list_view, name='vendor-list'),
    path("vendor/<vid>", vendor_detail_view, name='vendor-detail'),

    # Tags
    path("tags/<slug:tag_slug>", tag_list, name='tag-list'),

    # Reviews,
    path("ajax_add_review/<int:pid>", ajax_add_review, name='ajax_add_review'),

    # Search
    path("search", search_view, name='search'),
    path("vendor-search", vendor_search_view, name="vendor-search"),

    # Filter Products
    path("filter-products", filter_product, name='filter-product'),

    # Add to cart
    path("add-to-cart", add_to_cart_view, name='add-to-cart'),

    # Cart page
    path("cart", cart_view, name='cart'),

    # Delete product from cart page
    path("delete-from-cart", delete_product_from_cart, name='delete-from-cart'),

    # Update quantity
    path("update-cart", update_cart, name='update-cart'),

    # Checkout page
    path("checkout", checkout, name='checkout'),

    # Paypal
    path("paypal/", include('paypal.standard.ipn.urls')),

    # Successful payment
    path("payment-success", paypal_success, name="payment-success"),

    # Failed payment
    path("payment-failed", paypal_fail, name="payment-failed"),

    # User dashboard
    path("dashboard", user_dashboard, name="dashboard"),

    # Order detail
    path("dashboard/order/<int:pk>", order_detail, name="order-detail"),

    # Make default address
    path("make-default-address", make_default_address, name="make-default-address"),

    # Empty cart
    path("empty-cart", empty_cart, name="empty-cart"),

    # Add to wishlist
    path("add-to-wishlist", add_to_wishlist, name="add-to-wishlist"),

    # View wishlist
    path("wishlist", wishlist_view, name="wishlist"),

    # Remove from wishlist
    path("remove-from-wishlist", remove_from_wishlist, name="remove-from-wishlist"),

    # About Us
    path("about-us", about_us_view, name="about-us"),

    # Blog List
    path("blogs", blog_list_view, name="blog-list"),

    # All Deals
    path("all-deals", all_deals_view, name="all-deals"),
    path('add-new-review/', add_new_review, name='add-new-review'),
    path('add-new-reply/', add_new_reply, name='add-new-reply'),
]

userauths/urls.py
from django.urls import path
from userauths.views import *

app_name = 'userauths'
urlpatterns = [
    path('user/sign-up', sign_up_view, name='sign-up'),
    path('user/sign-in', sign_in_view, name='sign-in'),
    path('user/sign-out', sign_out_view, name='sign-out'),
    path('user/contact-us', contact_us, name="contact-us"),
    path('contact-us-ajax', ajax_contact_us, name="contact-us-ajax"),
    path('edit-profile', edit_profile, name="edit-profile"),
    path('change-password', change_password, name='change-password'),
]

core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Comment', 'id': 'text'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.db.models.functions import ExtractMonth
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from core.models import Product, ProductReview, CartOrder, Category, Address, Vendor, Wishlist, \
    CartOrderItems
from userauths.models import Profile
from taggit.models import Tag
from django.db.models import Count, Avg
from core.forms import ProductReviewForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import calendar
from userauths.models import User


def home_view(request):
    return render(request, 'core/index.html')


def product_list_view(request):
    products = Product.objects.filter(product_status='published')
    return render(request, 'core/product-list.html', {'products': products})


def category_list_view(request):
    categories = Category.objects.all()
    return render(request, 'core/category-list.html', {'categories': categories})


def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status='published', category=category)

    return render(request, 'core/category-product-list.html', {'category': category, 'products': products})


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    return render(request, 'core/vendors-list.html', {'vendors': vendors})


def vendor_detail_view(request, vid):
    vendor = get_object_or_404(Vendor, vid=vid)
    products = Product.objects.filter(product_status='published', vendor=vendor)
    return render(request, 'core/vendor-details.html',
                  {'vendor': vendor, 'products': products, })


def rating_to_width(avg_rating):
    if not (1 <= avg_rating <= 5):
        raise ValueError("Average rating must be between 1 and 5.")

    widths = {1: 20, 2: 40, 3: 60, 4: 80, 5: 100}
    base_width = widths[int(avg_rating)]
    decimal_part = avg_rating - int(avg_rating)

    if decimal_part == 0:
        return base_width
    else:
        additional_width = 10 if decimal_part <= 0.5 else 20
        return base_width + additional_width - (10 * (0.5 - decimal_part) if decimal_part < 0.5 else 0)


def product_detail_view(request, pid):
    product = get_object_or_404(Product, pid=pid)
    product_images = product.images.all()
    related_products = Product.objects.filter(category=product.category).exclude(pid=pid)
    products = Product.objects.all().order_by('-date').exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product, review_status="published").order_by("-date")
    total_reviews = reviews.count()
    # Calculate counts for each rating value
    rating_counts = reviews.values('rating').annotate(count=Count('rating')).order_by('rating')
    # Initialize dictionary to hold percentage of each rating
    rating_percentages = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
    # Calculate percentage for each rating
    for rating in rating_counts:
        if total_reviews > 0:
            rating_percentages[rating['rating']] = (rating['count'] / total_reviews) * 100
    avg_rating = ProductReview.objects.filter(product=product, review_status="published").aggregate(
        rating=Avg('rating'))
    if avg_rating['rating'] is not None:
        rating_width = rating_to_width(avg_rating['rating'])
    else:
        rating_width = 0
    review_form = ProductReviewForm()
    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False
    return render(request, 'core/product-detail.html',
                  {'product': product, 'product_images': product_images,
                   'related_products': related_products, 'products': products, 'reviews': reviews,
                   'avg_rating': avg_rating, 'review_form': review_form, 'make_review': make_review,
                   'rating_width': rating_width, 'rating_percentages': rating_percentages, })


def tag_list(request, tag_slug):
    products = Product.objects.filter(product_status='published').order_by('-id')
    tag = get_list_or_404(Tag, slug=tag_slug)
    products = products.filter(tags__in=tag)
    return render(request, 'core/tag.html', {'tag': tag, 'products': products})


def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST.get('review'),
        rating=request.POST.get('rating'),
    )
    context = {
        'user': user.username,
        'review': request.POST.get('review'),
        'rating': request.POST.get('rating'),
    }
    avg_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    avg_reviews = avg_reviews.get('rating')
    return JsonResponse(
        {
            'bool': True,
            'context': context,
            'avg_reviews': avg_reviews,
        }
    )


def search_view(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query).order_by('-date')
    return render(request, 'core/search.html', {'products': products, 'query': query})


def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')
    tags = request.GET.getlist('tag[]')
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    products = Product.objects.filter(product_status='published').order_by('-date').distinct()
    products = products.filter(price__gte=min_price, price__lte=max_price)
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    if len(tags) > 0:
        products = products.filter(tags__id__in=tags).distinct()

    data = render_to_string("core/async/product-list.html", {'products': products})

    return JsonResponse({'data': data})


def add_to_cart_view(request):
    cart_product = {}
    cart_product[str(request.GET.get('id'))] = {
        'title': request.GET.get('title'),
        'quantity': request.GET.get('quantity'),
        'price': request.GET.get('price'),
        'pid': request.GET.get('pid'),
        'image': request.GET.get('image'),
    }
    if 'cart' in request.session:
        if str(request.GET.get('id')) in request.session['cart']:
            cart_data = request.session['cart']
            cart_data[str(request.GET.get('id'))]['quantity'] = int(
                cart_product[str(request.GET.get('id'))]['quantity'])
            cart_data.update(cart_data)
            request.session['cart'] = cart_data
        else:
            cart_data = request.session['cart']
            cart_data.update(cart_product)
            request.session['cart'] = cart_data
    else:
        request.session['cart'] = cart_product
    context = render_to_string('core/async/cart-list.html', {'cart': request.session['cart']})
    cart_total_amount = 0
    for product_id, item in request.session['cart'].items():
        cart_total_amount += int(item['quantity']) * (float(item['price']))
    return JsonResponse({
        'data': request.session['cart'],
        'context': context,
        'total_items': len(request.session['cart']),
        'cart_total_amount': cart_total_amount,
    })


def cart_view(request):
    if 'cart' in request.session:
        return render(request, 'core/cart.html',
                      {'cart': request.session['cart'],
                       'total_items': len(request.session['cart'])})
    else:
        return render(request, 'core/cart.html', {})


def delete_product_from_cart(request):
    product_id = str(request.GET.get('id'))
    if 'cart' in request.session:
        if product_id in request.session['cart']:
            del request.session['cart'][product_id]
            request.session.modified = True
    cart_total_amount = 0
    for product_id, item in request.session['cart'].items():
        cart_total_amount += int(item['quantity']) * (float(item['price']))
    # context = render_to_string('core/async/cart-list.html', {'cart': request.session['cart'],
    #                                                          'total_items': len(request.session['cart']),
    #                                                          'cart_total_amount': cart_total_amount})
    return JsonResponse({
        # 'mydata': context,
        'total_items': len(request.session['cart']),
        'cart_total_amount': cart_total_amount
    })


def update_cart(request):
    product_id = str(request.GET.get('id'))
    product_quantity = request.GET.get('quantity')
    if 'cart' in request.session:
        if product_id in request.session['cart']:
            request.session['cart'][str(request.GET.get('id'))]['quantity'] = product_quantity
            request.session.modified = True
    cart_total_amount = 0
    for product_id, item in request.session['cart'].items():
        cart_total_amount += int(item['quantity']) * (float(item['price']))
    # context = render_to_string('core/async/cart-list.html', {'cart': request.session['cart']})
    return JsonResponse({
        # 'mydata': context,
        'total_items': len(request.session['cart']),
        'cart_total_amount': float(cart_total_amount),
        'product_quantity': product_quantity,
    })


@login_required
def checkout(request):
    if 'cart' in request.session:
        if len(request.session['cart']) > 0:
            return render(request, 'core/checkout.html',
                          {'cart': request.session['cart'],
                           'total_items': len(request.session['cart'])})
    else:

templates/core/products-compare.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'home:home' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Compare
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <h1 class="heading-2 mb-10">Products Compare</h1>
                    <h6 class="text-body mb-40">There are <span
                            class="text-brand my-total-items">{{ total_items }}</span> products to compare</h6>
                    <div class="cart-action d-flex justify-content-between">
                        <a class="btn " href="{% url 'home:product-list' %}"><i class="fi-rs-arrow-left mr-10"></i>Continue
                            Shopping</a>
                    </div>
                    {% if compare.items %}
                        <div class="table-responsive">
                            <table class="table text-center table-compare">
                                <tbody>
                                <tr class="pr_image">
                                    <td class="text-muted font-sm fw-600 font-heading mw-200">Preview</td>
                                    {% for product_id, item in compare.items %}
                                        <td class="row_img image-row-{{ product_id }}"><a
                                                href="{% url 'home:product-detail' item.pid %}"><img
                                                src="{{ item.image }}"
                                                alt="compare-img"/></a></td>
                                    {% endfor %}
                                </tr>
                                <tr class="pr_title">
                                    <td class="text-muted font-sm fw-600 font-heading">Name</td>
                                    {% for product_id, item in compare.items %}
                                        <td class="product_name title-row-{{ product_id }}">
                                            <h6><a href="{% url 'home:product-detail' item.pid %}"
                                                   class="text-heading">{{ item.title }}</a></h6>
                                        </td>
                                    {% endfor %}
                                </tr>
                                <tr class="pr_price">
                                    <td class="text-muted font-sm fw-600 font-heading">Price</td>
                                    {% for product_id, item in compare.items %}
                                        <td class="product_price price-row-{{ product_id }}">
                                            <h4 class="price text-brand">${{ item.price }}</h4>
                                        </td>
                                    {% endfor %}
                                </tr>
                                {#                            <tr class="pr_rating">#}
                                {#                                <td class="text-muted font-sm fw-600 font-heading">Rating</td>#}
                                {#                                <td>#}
                                {#                                    <div class="rating_wrap">#}
                                {#                                        <div class="product-rate d-inline-block">#}
                                {#                                            <div class="product-rating" style="width: 90%"></div>#}
                                {#                                        </div>#}
                                {#                                        <span class="rating_num">(121)</span>#}
                                {#                                    </div>#}
                                {#                                </td>#}
                                {#                                <td>#}
                                {#                                    <div class="rating_wrap">#}
                                {#                                        <div class="product-rate d-inline-block">#}
                                {#                                            <div class="product-rating" style="width: 90%"></div>#}
                                {#                                        </div>#}
                                {#                                        <span class="rating_num">(35)</span>#}
                                {#                                    </div>#}
                                {#                                </td>#}
                                {#                                <td>#}
                                {#                                    <div class="rating_wrap">#}
                                {#                                        <div class="product-rate d-inline-block">#}
                                {#                                            <div class="product-rating" style="width: 90%"></div>#}
                                {#                                        </div>#}
                                {#                                        <span class="rating_num">(125)</span>#}
                                {#                                    </div>#}
                                {#                                </td>#}
                                {#                            </tr>#}
                                <tr class="description">
                                    <td class="text-muted font-sm fw-600 font-heading">Description</td>
                                    {% for product_id, item in compare.items %}
                                        <td class="row_text font-xs des-row-{{ product_id }}">
                                            <p class="font-sm text-muted">{{ item.description }}</p>
                                        </td>
                                    {% endfor %}
                                </tr>
                                <tr class="pr_stock">
                                    <td class="text-muted font-sm fw-600 font-heading">Stock status</td>
                                    {% for product_id, item in compare.items %}
                                        {% if item.in_stock == 'True' %}
                                            <td class="row_stock stock-row-{{ product_id }}"><span
                                                    class="stock-status in-stock mb-0">In Stock</span>
                                            </td>
                                        {% elif item.in_stock == "False" %}
                                            <td class="row_stock stock-row-{{ product_id }}">
                                            <span class="stock-status out-stock mb-0">Out of stock</span>
                                        {% endif %}
                                    {% endfor %}
                                    </td>
                                </tr>
                                {#                            <tr class="pr_weight">#}
                                {#                                <td class="text-muted font-sm fw-600 font-heading">Weight</td>#}
                                {#                                <td class="row_weight">320 gram</td>#}
                                {#                                <td class="row_weight">370 gram</td>#}
                                {#                                <td class="row_weight">380 gram</td>#}
                                {#                            </tr>#}
                                {#                            <tr class="pr_dimensions">#}
                                {#                                <td class="text-muted font-sm fw-600 font-heading">Dimensions</td>#}
                                {#                                <td class="row_dimensions">N/A</td>#}
                                {#                                <td class="row_dimensions">N/A</td>#}
                                {#                                <td class="row_dimensions">N/A</td>#}
                                {#                            </tr>#}
                                <tr class="pr_add_to_cart">
                                    <td class="text-muted font-sm fw-600 font-heading">Buy now</td>
                                    {% for product_id, item in compare.items %}
                                        {% if item.in_stock == 'True' %}
                                            <td class="row_btn add-row-{{ product_id }}">
                                                <input type="hidden"
                                                       class="product-quantity-{{ product_id }}"
                                                       value="1"/>
                                                <input type="hidden"
                                                       class="product-pid-{{ product_id }}"
                                                       value="{{ item.pid }}"/>
                                                <input type="hidden"
                                                       class="product-image-{{ product_id }}"
                                                       value="{{ item.image }}"/>
                                                <input type="hidden" class="product-id-{{ product_id }}"
                                                       value="{{ product_id }}"/>
                                                <input type="hidden"
                                                       class="product-title-{{ product_id }}"
                                                       value="{{ item.title }}"/>
                                                <input type="hidden"
                                                       class="product-in-stock-{{ product_id }}"
                                                       value="{{ item.in_stock }}"/>
                                                <input type="hidden"
                                                       class="product-description-{{ product_id }}"
                                                       value="{{ item.description }}"/>
                                                <input type="hidden" id="current-product-price-{{ product_id }}"
                                                       value="{{ item.price|floatformat }}">
                                                {% if request.session.cart and product_id|stringformat:"s" in request.session.cart %}
                                                    <a class="remove remove-from-cart"
                                                       data-index="{{ product_id }}"
                                                       data-product-id="{{ product_id }}"><i
                                                            class="fi-rs-trash mr-5"
                                                            style="color: white;"></i></a>
                                                {% else %}
                                                    <a class="btn btn-sm my-add-to-cart" data-index="{{ product_id }}"
                                                       data-product-id="{{ product_id }}"><i
                                                            class="fi-rs-shopping-bag mr-5"></i>Add to
                                                        cart
                                                    </a>
                                                {% endif %}
                                            </td>
                                        {% elif item.in_stock == "False" %}
                                            <td class="row_btn add-row-{{ product_id }}">
                                                <a href="{% url 'userauths:contact-us' %}"
                                                   class="btn btn-sm btn-secondary"><i
                                                        class="fi-rs-headset mr-5"></i>Contact
                                                    Us
                                                </a>
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                                <tr class="pr_remove text-muted">
                                    <td class="text-muted font-md fw-600"></td>
                                    {% for product_id ,item in compare.items %}
                                        <td class="row_remove remove-row-{{ product_id }}">
                                            <a class="text-muted remove-from-compare"
                                               data-product-id="{{ product_id }}"><i
                                                    class="fi-rs-trash mr-5"></i><span>Remove</span>
                                            </a>
                                        </td>
                                    {% endfor %}
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
{% endblock content %}