Nest_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path("iViR0s08y6h{Q6[!Sxnw@(/", admin.site.urls),
    path("", include('core.urls')),
    path("", include('userauths.urls')),
    path("api/", include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import *
from rest_framework import routers

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'categories', CategoryViewSet, basename='categories')

# urlpatterns = router.urls
urlpatterns = [
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('test/', test_end_point, name='test'),
    path('', get_routes),
]

core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'home'
urlpatterns = [
    # Home page
    path("", home_view, name='home'),

    # Products
    path("products", product_list_view, name='product-list'),
    path("product/<pid>", product_detail_view, name="product-detail"),
    path("compare", compare_products_view, name="compare"),
    path("add-to-compare", add_to_compare, name="add-to-compare"),
    path("delete-from-compare", delete_product_from_compare, name="delete-from-compare"),

    # Categories
    path("categories", category_list_view, name='category-list'),
    path("<cid>/products", category_product_list_view, name='category_product_list'),

    # Vendors
    path("vendors", vendor_list_view, name='vendor-list'),
    path("vendor/<vid>", vendor_detail_view, name='vendor-detail'),

    # Tags
    path("tags/<slug:tag_slug>", tag_list, name='tag-list'),

    # Reviews,
    path("ajax_add_review/<int:pid>", ajax_add_review, name='ajax_add_review'),

    # Search
    path("search", search_view, name='search'),
    path("vendor-search", vendor_search_view, name="vendor-search"),

    # Filter Products
    path("filter-products", filter_product, name='filter-product'),

    # Add to cart
    path("add-to-cart", add_to_cart_view, name='add-to-cart'),

    # Cart page
    path("cart", cart_view, name='cart'),

    # Delete product from cart page
    path("delete-from-cart", delete_product_from_cart, name='delete-from-cart'),

    # Update quantity
    path("update-cart", update_cart, name='update-cart'),

    # Checkout page
    path("checkout", checkout, name='checkout'),

    # Paypal
    path("paypal/", include('paypal.standard.ipn.urls')),

    # Successful payment
    path("payment-success", paypal_success, name="payment-success"),

    # Failed payment
    path("payment-failed", paypal_fail, name="payment-failed"),

    # User dashboard
    path("dashboard", user_dashboard, name="dashboard"),

    # Order detail
    path("dashboard/order/<int:pk>", order_detail, name="order-detail"),

    # Make default address
    path("make-default-address", make_default_address, name="make-default-address"),

    # Empty cart
    path("empty-cart", empty_cart, name="empty-cart"),

    # Add to wishlist
    path("add-to-wishlist", add_to_wishlist, name="add-to-wishlist"),

    # View wishlist
    path("wishlist", wishlist_view, name="wishlist"),

    # Remove from wishlist
    path("remove-from-wishlist", remove_from_wishlist, name="remove-from-wishlist"),

    # About Us
    path("about-us", about_us_view, name="about-us"),

    # Blog List
    path("blogs", blog_list_view, name="blog-list"),

    # All Deals
    path("all-deals", all_deals_view, name="all-deals"),
    path('add-new-review/', add_new_review, name='add-new-review'),
    path('add-new-reply/', add_new_reply, name='add-new-reply'),
]

userauths/urls.py
from django.urls import path
from userauths.views import *

app_name = 'userauths'
urlpatterns = [
    path('user/sign-up', sign_up_view, name='sign-up'),
    path('user/sign-in', sign_in_view, name='sign-in'),
    path('user/sign-out', sign_out_view, name='sign-out'),
    path('user/contact-us', contact_us, name="contact-us"),
    path('contact-us-ajax', ajax_contact_us, name="contact-us-ajax"),
    path('edit-profile', edit_profile, name="edit-profile"),
    path('change-password', change_password, name='change-password'),
]

userauths/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.utils.safestring import mark_safe


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    phone = models.CharField(max_length=11, unique=True, validators=[])

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def profile(self):
        profile = Profile.objects.get(user=self)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    display_name = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to='profile_pictures')
    verified = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    post_save.connect(create_user_profile, sender=User)
    post_save.connect(save_user_profile, sender=User)

    def __str__(self):
        return self.full_name

    def user_image(self):
        return mark_safe('<img src="%s" width="50"  height="50" />' % self.image.url)


class ContactUs(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    class Meta:
        verbose_name_plural = 'Contact Us'

    def __str__(self):
        return self.full_name

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import *
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    phone = forms.CharField(max_length=50, min_length=11, widget=forms.TextInput(attrs={'placeholder': 'Phone number'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'phone']


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['full_name', 'display_name', 'bio', 'image']


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(max_length=200,
                                       widget=forms.PasswordInput(attrs={'placeholder': 'Enter your current password'}))
    password1 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Enter your new password'}))
    password2 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your new password'}))

    # def clean_current_password(self):
    #     current_password = self.cleaned_data.get('current')
    #     email = self.cleaned_data.get('user-email')
    #     user = User.objects.filter(email=email, password=current_password)
    #     if user.exists():
    #         return current_password
    #     raise ValidationError("Please enter your password correctly", code="current_password_wrong")

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise ValidationError('Passwords are not the same..', code='not_same_password')
        return password1

userauths/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from userauths.models import *
from django.http import JsonResponse
from userauths.forms import *


def sign_up_view(request):
    if request.user.is_authenticated:
        messages.warning(request, "You're already Logged In.")
        return redirect('home:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Hello {username}, your account created successfully.")
            new_user = authenticate(username=form.cleaned_data.get('email'),
                                    password=form.cleaned_data.get('password1'))
            login(request, new_user)
            return redirect('home:home')
    else:
        form = SignUpForm()
    return render(request, 'userauths/sign_up.html', {'form': form})


def sign_in_view(request):
    if request.user.is_authenticated:
        messages.warning(request, "You're already Logged In.")
        return redirect('home:home')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            messages.success(request, f"You're logged in successfully.")
            login(request, user)
            return redirect('home:home')
        else:
            messages.warning(request, "User doesn't exist, create account.")
    return render(request, 'userauths/sign_in.html', {})


def sign_out_view(request):
    logout(request)
    messages.success(request, "You're logged out successfully.")
    return redirect('home:home')


def contact_us(request):
    return render(request, 'userauths/contact_us.html', {})


def ajax_contact_us(request):
    full_name = request.GET.get('full_name')
    email = request.GET.get('email')
    phone = request.GET.get('phone')
    subject = request.GET.get('subject')
    message = request.GET.get('message')
    ContactUs.objects.create(
        full_name=full_name,
        email=email,
        phone=phone,
        subject=subject,
        message=message
    )
    return JsonResponse({
        'boolean': True
    })


@login_required
def edit_profile(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None

    if request.method == "POST":
        form = EditProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('home:dashboard')
    else:
        form = EditProfileForm(instance=profile)
    return render(request, 'userauths/edit-profile.html', {'form': form, 'profile': profile})


@login_required
def change_password(request):
    if request.method == 'POST':
        form1 = ChangePasswordForm(request.POST)
        if form1.is_valid():
            user = request.user
            user.password = form1.cleaned_data.get('password1')
            user.save()
            logout(request)
            return redirect('userauths:sign-in')
    else:
        form1 = ChangePasswordForm()
    return render(request, 'userauths/change-password.html', {'form1': form1})

templates/userauths/contact_us.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'home:home' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> Contact
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="row">
                    <div class="col-xl-10 col-lg-12 m-auto">
                        <section class="row align-items-end mb-50">
                            <div class="col-lg-4 mb-lg-0 mb-md-5 mb-sm-5">
                                <h4 class="mb-20 text-brand">How can help you ?</h4>
                                <h1 class="mb-30">Let us know how we can help you</h1>
                                {#                                <p class="mb-20">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit#}
                                {#                                    tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec#}
                                {#                                    ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                            </div>#}
                                {#                            <div class="col-lg-8">#}
                                {#                                <div class="row">#}
                                {#                                    <div class="col-lg-6 mb-4">#}
                                {#                                        <h5 class="mb-20">01. Visit Feedback</h5>#}
                                {#                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus,#}
                                {#                                            luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                                    </div>#}
                                {#                                    <div class="col-lg-6 mb-4">#}
                                {#                                        <h5 class="mb-20">02. Employer Services</h5>#}
                                {#                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus,#}
                                {#                                            luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                                    </div>#}
                                {#                                    <div class="col-lg-6 mb-lg-0 mb-4">#}
                                {#                                        <h5 class="mb-20 text-brand">03. Billing Inquiries</h5>#}
                                {#                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus,#}
                                {#                                            luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                                    </div>#}
                                {#                                    <div class="col-lg-6">#}
                                {#                                        <h5 class="mb-20">04.General Inquiries</h5>#}
                                {#                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus,#}
                                {#                                            luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>#}
                                {#                                    </div>#}
                                {#                                </div>#}
                            </div>
                        </section>
                    </div>
                </div>
            </div>
            {#            <section class="container mb-50 d-none d-md-block">#}
            {#                <div class="border-radius-15 overflow-hidden">#}
            {#                    <div id="map-panes" class="leaflet-map"></div>#}
            {#                </div>#}
            {#            </section>#}
            <div class="container">
                <div class="row">
                    <div class="col-xl-10 col-lg-12 m-auto">
                        <section class="mb-50">
                            <div class="row mb-60">
                                <div class="col-md-4 mb-4 mb-md-0">
                                    <h4 class="mb-15 text-brand">Office</h4>
                                    205 North Michigan Avenue, Suite 810<br/>
                                    Chicago, 60601, USA<br/>
                                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br/>
                                    <abbr title="Email">Email: </abbr>contact@Evara.com<br/>
                                    <a class="btn btn-sm font-weight-bold text-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i
                                            class="fi-rs-marker mr-5"></i>View map</a>
                                </div>
                                <div class="col-md-4 mb-4 mb-md-0">
                                    <h4 class="mb-15 text-brand">Studio</h4>
                                    205 North Michigan Avenue, Suite 810<br/>
                                    Chicago, 60601, USA<br/>
                                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br/>
                                    <abbr title="Email">Email: </abbr>contact@Evara.com<br/>
                                    <a class="btn btn-sm font-weight-bold text-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i
                                            class="fi-rs-marker mr-5"></i>View map</a>
                                </div>
                                <div class="col-md-4">
                                    <h4 class="mb-15 text-brand">Shop</h4>
                                    205 North Michigan Avenue, Suite 810<br/>
                                    Chicago, 60601, USA<br/>
                                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br/>
                                    <abbr title="Email">Email: </abbr>contact@Evara.com<br/>
                                    <a class="btn btn-sm font-weight-bold text-white mt-20 border-radius-5 btn-shadow-brand hover-up"><i
                                            class="fi-rs-marker mr-5"></i>View map</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-8">
                                    <h4 class="text-success message-sent"></h4>
                                    <div class="contact-from-area padding-20-row-col hide-contact-form">
                                        <h5 class="text-brand mb-10">Contact form</h5>
                                        <h2 class="mb-10">Drop Us a Line</h2>
                                        <p class="text-muted mb-30 font-sm">Your email address will not be published.
                                            Required fields are marked *</p>
                                        <form class="contact-form-style mt-30" id="contact-us-form" method="POST">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-6 col-md-6">
                                                    <div class="input-style mb-20">
                                                        <input required name="fullname" id="full-name" placeholder="Full Name"
                                                               type="text"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <div class="input-style mb-20">
                                                        <input required name="email" id="email" placeholder="Your Email"
                                                               type="email"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <div class="input-style mb-20">
                                                        <input name="phone" id="phone" placeholder="Your Phone"
                                                               type="tel"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <div class="input-style mb-20">
                                                        <input required name="subject" id="subject" placeholder="Subject"
                                                               type="text"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12">
                                                    <div class="textarea-style mb-30">
                                                        <textarea required name="message" id="message"
                                                                  placeholder="Message"></textarea>
                                                    </div>
                                                    <button class="submit submit-auto-width" type="submit">Send
                                                        message
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                        <p class="form-messege"></p>
                                    </div>
                                </div>
                                <div class="col-lg-4 pl-50 d-lg-block d-none">
                                    <img class="border-radius-15 mt-50"
                                         src="{% static 'assets/imgs/page/contact-2.png' %}" alt=""/>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/userauths/sign_in.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'home:home' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt=""/>
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create
                                                here</a></p>
                                        </div>
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required="" name="email"
                                                       placeholder="Username or Email *"/>
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password"
                                                       placeholder="Your password *"/>
                                            </div>
                                            {#                                            <div class="login_footer form-group">#}
                                            {#                                                <div class="chek-form">#}
                                            {#                                                    <input type="text" placeholder="Security code *"/>#}
                                            {#                                                </div>#}
                                            {#                                                <span class="security-code">#}
                                            {#                                                    <b class="text-new">8</b>#}
                                            {#                                                    <b class="text-hot">6</b>#}
                                            {#                                                    <b class="text-sale">7</b>#}
                                            {#                                                    <b class="text-best">5</b>#}
                                            {#                                                </span>#}
                                            {#                                            </div>#}
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox"
                                                               id="exampleCheckbox1" value=""/>
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                                    </div>
                                                </div>
                                                <a class="text-muted" href="#">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up"
                                                        name="login">Log in
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}