Nest_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path("iViR0s08y6h{Q6[!Sxnw@(/", admin.site.urls),
    path("", include('core.urls')),
    path("", include('userauths.urls')),
    path("api/", include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import *
from rest_framework import routers

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'categories', CategoryViewSet, basename='categories')

# urlpatterns = router.urls
urlpatterns = [
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('test/', test_end_point, name='test'),
    path('', get_routes),
]

core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'home'
urlpatterns = [
    # Home page
    path("", home_view, name='home'),

    # Products
    path("products", product_list_view, name='product-list'),
    path("product/<pid>", product_detail_view, name="product-detail"),
    path("compare", compare_products_view, name="compare"),
    path("add-to-compare", add_to_compare, name="add-to-compare"),
    path("delete-from-compare", delete_product_from_compare, name="delete-from-compare"),

    # Categories
    path("categories", category_list_view, name='category-list'),
    path("<cid>/products", category_product_list_view, name='category_product_list'),

    # Vendors
    path("vendors", vendor_list_view, name='vendor-list'),
    path("vendor/<vid>", vendor_detail_view, name='vendor-detail'),

    # Tags
    path("tags/<slug:tag_slug>", tag_list, name='tag-list'),

    # Reviews,
    path("ajax_add_review/<int:pid>", ajax_add_review, name='ajax_add_review'),

    # Search
    path("search", search_view, name='search'),
    path("vendor-search", vendor_search_view, name="vendor-search"),

    # Filter Products
    path("filter-products", filter_product, name='filter-product'),

    # Add to cart
    path("add-to-cart", add_to_cart_view, name='add-to-cart'),

    # Cart page
    path("cart", cart_view, name='cart'),

    # Delete product from cart page
    path("delete-from-cart", delete_product_from_cart, name='delete-from-cart'),

    # Update quantity
    path("update-cart", update_cart, name='update-cart'),

    # Checkout page
    path("checkout", checkout, name='checkout'),

    # Paypal
    path("paypal/", include('paypal.standard.ipn.urls')),

    # Successful payment
    path("payment-success", paypal_success, name="payment-success"),

    # Failed payment
    path("payment-failed", paypal_fail, name="payment-failed"),

    # User dashboard
    path("dashboard", user_dashboard, name="dashboard"),

    # Order detail
    path("dashboard/order/<int:pk>", order_detail, name="order-detail"),

    # Make default address
    path("make-default-address", make_default_address, name="make-default-address"),

    # Empty cart
    path("empty-cart", empty_cart, name="empty-cart"),

    # Add to wishlist
    path("add-to-wishlist", add_to_wishlist, name="add-to-wishlist"),

    # View wishlist
    path("wishlist", wishlist_view, name="wishlist"),

    # Remove from wishlist
    path("remove-from-wishlist", remove_from_wishlist, name="remove-from-wishlist"),

    # About Us
    path("about-us", about_us_view, name="about-us"),

    # Blog List
    path("blogs", blog_list_view, name="blog-list"),

    # All Deals
    path("all-deals", all_deals_view, name="all-deals"),
    path('add-new-review/', add_new_review, name='add-new-review'),
    path('add-new-reply/', add_new_reply, name='add-new-reply'),
]

templates/includes/deals-of-day.html
<section class="section-padding pb-5">
    <div class="section-title">
        <h3 class="">Deals Of The Day</h3>
        <a class="show-all" href="{% url 'home:all-deals' %}">
            All Deals
            <i class="fi-rs-angle-right"></i>
        </a>
    </div>
    <div class="row">
        {% for product in deal_products|slice:"0:4" %}
            <div class="col-xl-3 col-lg-4 col-md-6">
                <div class="product-cart-wrap style-2">
                    <div class="product-img-action-wrap">
                        <div class="product-img">
                            <a href="{% url 'home:product-detail' product.pid %}">
                                <img src="{{ product.image.url }}" alt=""/>
                            </a>
                        </div>
                    </div>
                    <div class="product-content-wrap">
                        <div class="deals-countdown-wrap">
                            <div class="deals-countdown" data-countdown="2024/03/11"></div>
                        </div>
                        <div class="deals-content">
                            <h2>
                                <a href="{% url 'home:product-detail' product.pid %}">{{ product.title }}</a>
                            </h2>
                            <div class="product-rate-cover">
                                <div class="product-rate d-inline-block">
                                    <div class="product-rating" style="width: 90%"></div>
                                </div>
                                <span class="font-small ml-5 text-muted"> (4.0)</span>
                            </div>
                            <div>
                                                <span class="font-small text-muted">By <a
                                                        href="{% url 'home:vendor-detail' product.vendor.vid %}">{{ product.vendor.title }}</a></span>
                            </div>
                            <div class="product-card-bottom">
                                <div class="product-price">
                                    <span>$</span> <span
                                        id="current-product-price-{{ product.id }}">{{ product.price }}</span>
                                    <span class="old-price">${{ product.old_price }}</span>
                                </div>
                                <div class="add-cart">
                                    <input type="hidden"
                                           class="product-quantity-{{ product.id }}"
                                           value="1"/>
                                    <input type="hidden" class="product-pid-{{ product.id }}"
                                           value="{{ product.pid }}"/>
                                    <input type="hidden" class="product-image-{{ product.id }}"
                                           value="{{ product.image.url }}"/>
                                    <input type="hidden" class="product-id-{{ product.id }}"
                                           value="{{ product.id }}"/>
                                    <input type="hidden" class="product-title-{{ product.id }}"
                                           value="{{ product.title }}"/>
                                    <a class="add my-add-to-cart"
                                       data-index="{{ product.id }}"><i
                                            class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</section>